/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Address = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'zipCode' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'DISPATCHED' : IDL.Null,
  'PACKED' : IDL.Null,
  'PENDING' : IDL.Null,
  'DELIVERED' : IDL.Null,
  'CONFIRMED' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'principal' : IDL.Principal,
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'items' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'primaryName' : IDL.Text,
  'primaryEmail' : IDL.Text,
  'primaryPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAddress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAddress' : IDL.Func([IDL.Text], [IDL.Opt(Address)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Nat], [OrderStatus], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Address = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'zipCode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'DISPATCHED' : IDL.Null,
    'PACKED' : IDL.Null,
    'PENDING' : IDL.Null,
    'DELIVERED' : IDL.Null,
    'CONFIRMED' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'principal' : IDL.Principal,
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'items' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'primaryName' : IDL.Text,
    'primaryEmail' : IDL.Text,
    'primaryPhone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAddress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAddress' : IDL.Func([IDL.Text], [IDL.Opt(Address)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Nat], [OrderStatus], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };